/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AppNavbar: typeof import('./src/components/AppNavbar.vue')['default']
    AppNotifications: typeof import('./src/components/AppNotifications.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SeoAnalyzerForm: typeof import('./src/components/SeoAnalyzerForm.vue')['default']
    StatCard: typeof import('./src/components/StatCard.vue')['default']
    WorkflowCard: typeof import('./src/components/WorkflowCard.vue')['default']
  }
}
