# Zeabur 配置文件
services:
  leadio-api:
    build: .
    # 持久化存儲配置
    volumes:
      - /app/data:/data
    environment:
      # 存儲配置
      STORAGE_PATH: /data/reports
      STORAGE_TYPE: zeabur
      
      # 應用配置
      NODE_ENV: production
      PORT: 3001
      
      # 你的其他環境變數
      CLERK_PUBLISHABLE_KEY: ${CLERK_PUBLISHABLE_KEY}
      CLERK_SECRET_KEY: ${CLERK_SECRET_KEY}
      
      # 數據庫 (如果需要)
      DATABASE_URL: ${DATABASE_URL}
      
      # API 安全
      API_SECRET_KEY: ${API_SECRET_KEY}
      
    # 網路配置
    ports:
      - "3001:3001"
      
  # 如果你需要數據庫
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: leadio_api
      POSTGRES_USER: leadio
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: